on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build Serilog.Sinks.Kafka/ --configuration Release /p:Version=${VERSION} 
    - name: Pack
      run: dotnet pack Serilog.Sinks.Kafka/ --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push Serilog.Sinks.Kafka.${VERSION}.nupkg --source https://nuget.pkg.github.com/kekropp/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}